### ISSUE TITLE
[Suggestion] Clean up meaningless flow-typed stubs

### ISSUE THREAD

**Issue by cjies** [GSS-FED/vital-ui-kit-react#156]
## Issue Type

Other: suggestion

## Version of Vital UI Kit React

0.0.8-3

## Other details

Every modules that import from `node_modules/` are automatically type as `any` by flow, so the auto-generated stubs are not helping much in this project.

Maybe we can clean them up? Just keep some useful libdef like `styled-components`, `axios` and `rxjs` only.

**Comment by ericyip** [comment]
I found they have `--skip` flag for that
