### ISSUE TITLE
Apply lint check in pre-commit hook and CircleCI

### ISSUE THREAD

**Issue by cjies** [GSS-FED/vital-ui-kit-react#201]
**Is your feature request related to a problem? Please describe.**
Scanned whole repo, I found there have 48,965 lint problems, included 44,059 errors and 4,906 warnings.

**Describe the solution you'd like**
To maintain a product with strong quality, we should run prettier or eslint fix before committing or merging any files into master branch.

**Additional context**
1. Apply [husky](https://github.com/typicode/husky) and [lint-staged](https://github.com/okonet/lint-staged) to run lint check in pre-commit hook.
2. Run lint check in CircleCI.

**Comment by ericyip** [comment]
Should ignore `node_modules` and build file?

**Comment by cjies** [comment]
yup
