### ISSUE TITLE
Demo page's link is broken

### ISSUE THREAD

**Issue by mingjunlu** [GSS-FED/vital-ui-kit-react#665]
## Version of library
N/A

## Steps to Reproduce the Problem
1. Head to the Demo section of the README file
2. Click on "View Demo"

## Expected Behavior
The user should be brought to a demo page correctly.

## Actual Behavior
It only says `Not Found` there. The link seems to be broken.

## Other details
Here's a screenshot of the demo page.
![截圖 2020-06-03 下午12 18 46](https://user-images.githubusercontent.com/40516784/83595547-e097a980-a594-11ea-95a0-ff5655975b5e.png)

**Comment by caasi** [comment]
fixed: https://gss-fed.github.io/example-speed/

感謝回報～
