### ISSUE TITLE
釐清原本的 rollup.config.js 中使用的 plugins

### ISSUE THREAD

**Issue by caasi** [GSS-FED/vital-ui-kit-react#690]
各個 package 並不需要 [rollup-plugin-url][1] 和 [rollup-plugin-json][2] ，但原本的 rollup.config.js 中卻用上了。

好奇本來的需求是什麼？

[1]: https://www.npmjs.com/package/@rollup/plugin-url
[2]: https://www.npmjs.com/package/@rollup/plugin-json

**Comment by ericyip** [comment]
rollup-plugin-url 我記得是用在 avatar 的 svg, 後來改用 svgr 就沒用了

**Comment by caasi** [comment]
搜了一下沒看到有哪邊 import JSON ，那我先關掉了。
