### ISSUE TITLE
此專案在Windows上安裝時發生錯誤

### ISSUE THREAD

**Issue by a33068843** [GSS-FED/vital-ui-kit-react#709]
## Steps to Reproduce the Problem
1. 在 `cmd` 上執行 `yarn install`
2. 執行 `yarn bootstrap`
  
## Expected Behavior
不會出現錯誤訊息

## Actual Behavior
`yarn run v1.22.5`
`$ lerna bootstrap && yarn run build`
`lerna notice cli v3.22.1`
`lerna info bootstrap root only`
`[1/5] Validating package.json...`
`[2/5] Resolving packages...`
`success Already up-to-date.`
`$ yarn clean:build`
`$ lerna run clean --stream`
`lerna notice cli v3.22.1`
`lerna info Executing command in 16 packages: "yarn run clean"`
`@vital-ui/react-icon: $ rm -rf dist cjs types`
`@vital-ui/react-theme: $ rm -rf dist cjs types`
`@vital-ui/react-icon: 'rm' ���O�����Υ~���R�O�B�i���檺�{���Χ妸�ɡC`
`@vital-ui/react-icon: error Command failed with exit code 1.`
`@vital-ui/react-icon: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`
`lerna ERR! yarn run clean exited 1 in '@vital-ui/react-icon'`
`lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.`
`error Command failed with exit code 1.`
`info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`
`error Command failed with exit code 1.`
`info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`
`error Command failed with exit code 1.`
`info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by ericyip** [comment]
`rm -rf` 不支援 windows
可參考相關PR
https://github.com/GSS-FED/vital-ui-kit-react/pull/527
以我沒用win的經驗 加上 cross-env 應該即可

**Comment by caasi** [comment]
改用 `rimraf` 來移除建置結果了，你看看這樣在 Windows 上能不能跑？

**Comment by a33068843** [comment]
謝謝你們
可以正常運作了！
